-- Conectado como SVC_DBA ou SYS
CREATE SEQUENCE SVC_DBA.SEQ_GRANT_CONTROL START WITH 1 INCREMENT BY 1;

CREATE TABLE SVC_DBA.GRANT_CONTROL (
    ID              NUMBER DEFAULT SVC_DBA.SEQ_GRANT_CONTROL.NEXTVAL PRIMARY KEY,
    USUARIO_GRANTED VARCHAR2(128) NOT NULL,
    PRIVILEGIO      VARCHAR2(30)  NOT NULL,
    OBJETO          VARCHAR2(128) NOT NULL, -- Formato SCHEMA.TABELA
    GRANTOR         VARCHAR2(128) NOT NULL,
    DATA_SOLICITACAO DATE DEFAULT SYSDATE NOT NULL,
    DATA_EXPIRACAO   DATE DEFAULT SYSDATE + 15 NOT NULL,
    STATUS           VARCHAR2(20)  CHECK (STATUS IN ('SUCESSO', 'ERRO', 'REVOGADO')),
    OBSERVACOES      VARCHAR2(4000)
);

COMMENT ON TABLE SVC_DBA.GRANT_CONTROL IS 'Tabela de auditoria para sistema de Grants Automáticos';