services:
  ogm-web:
    build: .
    container_name: ogm-web
    ports:
      - "80:80"
    volumes:
      # O .env e o tns_catalog não precisam estar dentro da imagem
      # pois frequentemente precisam ser modificados e contêm dados sensíveis.
      - ./src/backend/.env:/usr/local/bin/.env:ro
      - ./src/backend/tns_catalog.conf:/usr/local/bin/tns_catalog.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/cgi-bin/index.cgi"]
      interval: 30s
      timeout: 10s
      retries: 3
