# [ID_DO_BANCO]|[LABEL_EXIBICAO_UI]|[STRING_DE_CONEXAO]
OGMLAB|Banco de Laboratório (OGMLAB)|(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=167.234.242.220)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=freepdb1)(INSTANCE_NAME=FREE)))
